apiVersion: v1
kind: Service
metadata:
  name: static-server2
spec:
  selector:
    app: static
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: static
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-deployment
  labels:
    app: static
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static
  template:
    metadata:
      name: static
      labels:
        app: static
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/enable-metrics-merging: "false"
    spec:
      containers:
        - name: static
          image: hashicorp/http-echo:latest
          args:
            - -text="hello world"
            - -listen=:8080
          ports:
            - containerPort: 8080
              name: http
      serviceAccountName: static
